### ISSUE TITLE
fitted values differs from x

### ISSUE THREAD

**Issue by Abri5** [mpascariu/MortalityLaws#16]
When using MortalityLaw() and then fitted(), the values are not corresponding to the true value. This also affect LifeTable()

library(MortalityLaws)
inf = 7
sup = 9
x = c(5:10)
qx = c(0.000436, 0.000438, 0.00044, 0.000443, 0.000446, 0.000449)
ml1 <- MortalityLaw(x, qx = qx, law = 'gompertz', fit.this.x = c(inf:sup))
ml1
coef(ml1)
fitted(ml1)

In the code I put values corresponding to ages 5 to 10, and fitting only 7 to 9 with Gompertz Law.
But when calling fitted() the corresponding values are not correct, the display values are 0.0004341233 for 5 (this must be 0 instead of 5), 0.0004370643 for 6 (this must be 1 instead of 6), ...

It seems that instead of using x=5 (and the respective value), it starts in x=0. This could not be a problem, but it also affect LifeTable() making the ages to be displaced. 

Using the coefficients and the formula for Gompertz, with x=5 the corresponding mu[x]=Aexp[Bx] value must be 0.00045207065

**Comment by mpascariu** [comment]
Hi @Abri5,
thanks for reaching out.
As you noticed the age range is scaled down in the fitting process mainly to obtain meaningful estimates and help in the optimization procedures. This is also described in the examples in the `??LawTable` function.

The life table should not be affected because in its construction we are taking into account this implemented scaling. Feel free to compare the obtained life table with the ones constructed using 'un-scaled' estimates and open the issue again if you notice errors.

Also is worth mentioning that the scaling is applied only to the 'laws' not covering the entire age range. See  `SCALE_X` column in `availableLaws()$table`.

**Comment by Abri5** [comment]
Wow, I see!
I totally missed that important note about the down scaling. 

Thank you for the convenient response c: Hope this closed “issue” helps other distracted people like me. 

Have a nice day/week/year/... and thanks for this usefull package!
